### ISSUE TITLE
Initial implementations for Login, Registration, SeaPod list, Map, Seapod Detail

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-admin-panel#1]
Everything is explained in this video: https://www.dropbox.com/s/d7khuvlgpeio1hj/2020-10-14%2014-59-28.mp4?dl=0

**Comment by shimaaelhosary** [comment]
Implemented responsive UI for login, register, and SeaPods pages.

**Comment by shimaaelhosary** [comment]
Implemented login, create account, auto login, and logout processes.

**Comment by shimaaelhosary** [comment]
Listing all seapods in mobile version.

**Comment by shimaaelhosary** [comment]
Added Google Map Configurations.

**Comment by shimaaelhosary** [comment]
Listed all seapods on the map with info window, Mobile version.
