### ISSUE TITLE
New Admin Panel for Multi-Pod

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-admin-panel#12]
Design doc for admin panel that does the following:

1. Gives  global views of all pods (Like current UI)
2. Allows access to pods as administrator

This is somewhat along the lines nabu casa

Acceptance Critera
----------------------
Design documentation that has diagrams and software required along with implementation of the above.

**Comment by scottdear** [comment]
Large T-Shirt size

**Comment by olagalal** [comment]
you can view the doc [here](https://docs.google.com/document/d/19UCCTcc7F-XiRBIpeUunaU0EZASbghe4aBJge4GxhM4/edit?usp=sharing), but it is not complete yet.

**Comment by scottdear** [comment]
Blocking on Getting Nabu Casa set up on ob-admin-panel#14 to complete research.

Options for multi-connect are:

1. VPN
2. Connect on-demand, (open internet port)
3. Connect on-demand, w/ OB gateway host, (internet open only to OB IP address)
4. Websocket
5. ssh tunnel

Also include pod user DB to OB user DB.

**Comment by scottdear** [comment]
This will use Apache as reverse proxy with mod_auth_openidc and cognito to solve the multi-user access, need to look into auto-provisioning.  Add diagram from @scottdear and @godslave05.

Also need @shimaaelhosary to post link to document in story.

**Comment by scottdear** [comment]
https://docs.google.com/document/d/19UCCTcc7F-XiRBIpeUunaU0EZASbghe4aBJge4GxhM4/edit?usp=sharing

Has been updated.

Will be updated to include the following:

@godslave05 's drawing w/ the ssh tunnel information.

A bit about the add-on to start the ssh tunnel.

**Comment by olagalal** [comment]
Final Doc, you can find it [here](https://docs.google.com/document/d/19UCCTcc7F-XiRBIpeUunaU0EZASbghe4aBJge4GxhM4/edit?usp=sharing) 
We can start with ssh add-on
