### ISSUE TITLE
Create Design Doc for SSO w/ Cognito/Apache/mod_auth_openidc

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-admin-panel#13]
Need a strategy to synchronize users between Pods and OB remote.

Acceptance Criteria
-----------------------
1. Design Doc that describes pieces needed and methods for securing remote users.
2. Must include reference to communication between users HA->OB and OB->HA.

**Comment by scottdear** [comment]
@godslave05 check this out:
https://developers.home-assistant.io/docs/frontend/external-authentication

We might be able to use that, e.g. we create an admin user on each pod that gets authenticated externally w/ a token that we generate.

What do you think about that, at least for the HTTP auth to the UI.

**Comment by scottdear** [comment]
OK I don't think we need to sync users, we might be able to do the following:
https://community.home-assistant.io/t/reverse-proxy-with-apache/196942
Then we'll add mod_auth_openidc
https://github.com/zmartzone/mod_auth_openidc
And it will local proxy to the tunneling that are turning in the github issue:
https://github.com/oceanbuilders/hass-addons/issues/1
We'll use the AWS Cognito Single Sign On Hosted UI I've created, at:
https://oceanbuilders.auth.us-west-1.amazoncognito.com

**Comment by scottdear** [comment]
@godslave05 will create a new design document that addresses the above and includes the new SSO design.  Included strategy for auto provisioning or pre-created admin user.

**Comment by godslave05** [comment]
I will attach the doc url here 
and close this issue
