### ISSUE TITLE
Updates README for OB App

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-admin-panel#6]
Put some nice stuff, bonus for pictures and links to tech used.

NOTE: This goes into the ob-flutter-ap repo.

Acceptance Criteria
-----------------------
Update README.md (markdown) in root directory of the ob-flutter-app repository to include the following:

1. List of features in the admin app
2. Add a list of features from the user app
3. Approprite screenshots
4. How to contribute.    -  Instructions about how open source contributors can check out source and make pull requests.
5. Add additional text about looking at issues, and contributing.

**Comment by angiedear** [comment]
Hi Shimaa, how's this issue coming along?  Can you give me an updated status?

**Comment by angiedear** [comment]
Hi Shimaa, can I get a status update for this issue please?

**Comment by shimaaelhosary** [comment]
Hi @angiedear, I asked for Hendrik help. He will send me some information about the admin panel and I will add the information about the tech used.

**Comment by scottdear** [comment]
@shimaaelhosary we're moving Hendricks designs to the backlog.  Our current effort needs to focus on identifying the admin app pieces that will be merged into the current user app.  We also need to solve the issue or supporting roles and permissions so that the UI elements are driven by the data that is behind the roles and permissions.  I can help w/ identifying the parts that are needed.  I'm not so interested in the tech as just a high level description of the bits of functionality, e.g. view event logs, admin access to user, etc.  Once we have the components identified we can start moving them over piece by piece.

**Comment by godslave05** [comment]
I will contribute by doing this 2 for the user-app
Add a list of features from the user app
Appropriate screenshots

**Comment by shimaaelhosary** [comment]
The doc link
https://docs.google.com/document/d/1QB6I_XdLR-wFrs0y36okTj9Ac6aeEAdHlniLyxiGx7s/edit

**Comment by scottdear** [comment]
Given new implementation, will need more changes on new issue.
