### ISSUE TITLE
Identify Admin-ui specific features to integrate w/ User app.

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-admin-panel#9]
We need to begin the effort of integrating admin UI features into the User App.

This may also involve adding tooling to make the User App UI more data driven.  What I mean by this is that , for example, pod owner,  guest, to OB admin to OB support (like admin but read only), Housekeeper, Property Manager, etc.  The idea is that the menus, canvases, dropdowns, buttons, etc. should be data driven.  What is in the data that drives the UI's is based on an authenticated users "Roles".  Each role will have associated with it a set of "Permissions" that will give them read/write,update, and or delete access to a given resource, e.g. a light, a switch, locks, etc.

Acceptance Criteria
------------------------
1. 1-2 page document that defines the features that will be brought across from the admin UI.  This will be a list of the pages, screens, and other functionality that we want to make sure is included in the unified app.

I took the second part out as it is a bit larger than one story can contain.  I opened #10 to address the design portion of the unified app.

**Comment by shimaaelhosary** [comment]
Here the doc link. 
https://docs.google.com/document/d/1YZR9u3tIrNJknZRD_N0QVkP-ljU5mxCJf2uDoNHUHMA/edit?usp=sharing
